name: Release

on:
  # NOTE: only run when a tag is pushed, like a new version to release
  push:
    tags:
      - "*"

  # NOTE: allows manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to CodeArtifact
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      # NOTE: we only need a few files not included in the artifact
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            pyproject.toml
            README.md

      # NOTE: get the built artifacts from the previous job
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - uses: actions/setup-python@v5
      - uses: snok/install-poetry@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::842500961385:role/github-oidc-githubactionsrole82740668-AHJKU1DJMRBH

      - name: Upload wheel to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: dist/*.whl
          tag: ${{github.ref}}
          overwrite: true
          file_glob: true

      - name: Publish with Poetry
        run: |
          export CA_REPO=$(aws codeartifact get-repository-endpoint --domain-owner 842500961385 --domain matterbeam --repository matterbeam-shared --format pypi --query 'repositoryEndpoint' --output text)
          export CA_TOKEN=$(aws codeartifact get-authorization-token --domain-owner 842500961385 --domain matterbeam --query 'authorizationToken' --output text)

          poetry config repositories.matterbeam-shared $CA_REPO
          poetry config pypi-token.matterbeam-shared $CA_TOKEN

          poetry publish -r matterbeam-shared
